version: '3'

services: 
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
    networks: 
      - node_network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_network
    ports:
      - 3306:3306

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: fermope/nginx:prod
    container_name: nginx
    networks: 
      - node_network
    ports: 
      - "8080:80"
    depends_on: 
       - app

networks: 
  node_network:
    driver: bridge      

volumes:
  mysql-data: